# Autogenerated wrapper script for MuJoCo_jll for x86_64-w64-mingw32
export libmujoconogl, libmujoco

using GLEW_jll
using GLFW_jll
using Libglvnd_jll
## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "PATH"

# Relative path to `libmujoconogl`
const libmujoconogl_splitpath = ["bin", "mujoco200nogl.dll"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libmujoconogl_path = ""

# libmujoconogl-specific global declaration
# This will be filled out by __init__()
libmujoconogl_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libmujoconogl = "mujoco200nogl.dll"


# Relative path to `libmujoco`
const libmujoco_splitpath = ["bin", "mujoco200.dll"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libmujoco_path = ""

# libmujoco-specific global declaration
# This will be filled out by __init__()
libmujoco_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libmujoco = "mujoco200.dll"


"""
Open all libraries
"""
function __init__()
    global prefix = abspath(joinpath(@__DIR__, ".."))

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    append!.(Ref(PATH_list), (GLEW_jll.PATH_list, GLFW_jll.PATH_list, Libglvnd_jll.PATH_list,))
    append!.(Ref(LIBPATH_list), (GLEW_jll.LIBPATH_list, GLFW_jll.LIBPATH_list, Libglvnd_jll.LIBPATH_list,))

    global libmujoconogl_path = abspath(joinpath(artifact"MuJoCo", libmujoconogl_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libmujoconogl_handle = dlopen(libmujoconogl_path)
    push!(LIBPATH_list, dirname(libmujoconogl_path))

    global libmujoco_path = abspath(joinpath(artifact"MuJoCo", libmujoco_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libmujoco_handle = dlopen(libmujoco_path)
    push!(LIBPATH_list, dirname(libmujoco_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ';')
    global LIBPATH = join(LIBPATH_list, ';')

    # Add each element of LIBPATH to our DL_LOAD_PATH (necessary on platforms
    # that don't honor our "already opened" trick)
    #for lp in LIBPATH_list
    #    push!(DL_LOAD_PATH, lp)
    #end
end  # __init__()

